<?php
/**
 * CardsPhysicalBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.78.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CardsPhysicalBodyTest Class Doc Comment
 *
 * @category    Class
 * @description CardsPhysicalBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardsPhysicalBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardsPhysicalBody"
     */
    public function testCardsPhysicalBody()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "device_ksn"
     */
    public function testPropertyDeviceKsn()
    {
    }

    /**
     * Test attribute "device_dukpt"
     */
    public function testPropertyDeviceDukpt()
    {
    }

    /**
     * Test attribute "cof_identifier"
     */
    public function testPropertyCofIdentifier()
    {
    }

    /**
     * Test attribute "original_ip"
     */
    public function testPropertyOriginalIp()
    {
    }
}
