<?php
/**
 * IvrSessionstateBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.78.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IvrSessionstateBodyTest Class Doc Comment
 *
 * @category    Class
 * @description IvrSessionstateBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IvrSessionstateBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IvrSessionstateBody"
     */
    public function testIvrSessionstateBody()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "ivr_provider_id"
     */
    public function testPropertyIvrProviderId()
    {
    }

    /**
     * Test attribute "ivr_merchant_order"
     */
    public function testPropertyIvrMerchantOrder()
    {
    }
}
