<?php
/**
 * V1CardsBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.78.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1CardsBodyTest Class Doc Comment
 *
 * @category    Class
 * @description V1CardsBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1CardsBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1CardsBody"
     */
    public function testV1CardsBody()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "cvc2"
     */
    public function testPropertyCvc2()
    {
    }

    /**
     * Test attribute "jet_token"
     */
    public function testPropertyJetToken()
    {
    }

    /**
     * Test attribute "expiry_year"
     */
    public function testPropertyExpiryYear()
    {
    }

    /**
     * Test attribute "expiry_month"
     */
    public function testPropertyExpiryMonth()
    {
    }

    /**
     * Test attribute "pan"
     */
    public function testPropertyPan()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "notify"
     */
    public function testPropertyNotify()
    {
    }

    /**
     * Test attribute "card_holder_name"
     */
    public function testPropertyCardHolderName()
    {
    }

    /**
     * Test attribute "secure_authentication"
     */
    public function testPropertySecureAuthentication()
    {
    }
}
